version: '3.9'

services:
  mev-boost-collector:
    container_name: mev-boost-monitoring-collector
    build:
      context: ./
      dockerfile: Dockerfile
    user: "${UID_GID}"
    tty: true
    restart: on-failure
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - "postgres:postgres"
    # command: [ "./bin/migrator" ]
    networks:
      - friendship

  postgres:
    image: postgres:14-alpine
    hostname: mev-boost-monitoring-postgres
    container_name: mev-boost-monitoring-postgres
    restart: always
    user: "${UID_GID}"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: master
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./storage/postgresql:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - friendship

networks:
  friendship:
    driver: bridge